import Link from 'next/link';
export default function Home() {
  return <main className="container page-space">
    <div className="notice warning v2-banner"><strong>V2A prototype:</strong> sample prices, not live store quotes. Try the budget workflow without an account or payment.</div>
    <section className="hero"><div><p className="eyebrow">LESS GUESSWORK. MORE ROOM IN YOUR BUDGET.</p><h1>Plan your week.<br />Compare your cart.<br /><span>Spend less.</span></h1><p className="hero-copy">A grocery budget should be a starting point, not a surprise at checkout. FitCart is being built to connect your budget, shopping choices and meals in one place.</p><div className="hero-actions"><Link href="/budget" className="button primary">Compare my cart <span aria-hidden="true">&rarr;</span></Link><Link href="/sample" className="button secondary">Explore a sample</Link></div><p className="help">Fitness is optional. Body measurements are not needed. Use sample answers to test without personal information.</p></div>
    <aside className="hero-preview"><p className="eyebrow">YOUR MONEY. YOUR TRADE-OFFS.</p><h2>What would a smarter shop look like?</h2><div className="preview-meal"><span>SET YOUR BOUNDARY</span><strong>A hard limit, a target, or lowest cost.</strong></div><div className="preview-meal"><span>COMPARE YOUR OPTIONS</span><strong>One stop, or an optional second store.</strong></div><div className="preview-meal"><span>USE WHAT WORKS FOR YOU</span><strong>Your pantry. Your appliances. Your choices.</strong></div><p className="notice">Publix / Walmart / Food Lion / ALDI<br /><small>Clemson-area concept. Retailer prices, branches and deals are not verified in this version.</small></p></aside></section>
    <section className="how-grid" aria-label="Budget-first workflow"><article><p className="eyebrow">01 / PLAN</p><h2>Put the budget first.</h2><p>Choose what you can spend, how many people you feed and where you would shop.</p></article><article><p className="eyebrow">02 / COMPARE</p><h2>See the trade-offs.</h2><p>Explore sample whole-package totals, pantry deductions and optional two-store combinations.</p></article><article><p className="eyebrow">03 / CHOOSE</p><h2>Keep control of every swap.</h2><p>Compare a lower-cost example before accepting a change. Healthy eating stays part of the idea; macro tracking is not the headline.</p></article></section>
    <section className="feedback-callout"><div><p className="eyebrow">BUILD WITH US</p><h2>Would this make your next grocery trip easier?</h2><p>Try the sample, then tell us what helped and what did not. Real pricing comes in V2B.</p></div><Link href="/feedback" className="button primary">Give prototype feedback</Link></section>
  </main>;
}
